//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Windows.Forms;


namespace NSDriver {
    
    public partial class driverForm : System.Windows.Forms.Form {
        #region fields
        /// <summary>
        /// Required designer variable.
        /// </summary>
        IContainer components = null;
        MenuStrip ms1;
        ToolStripMenuItem tsmiFile;
        ToolStripMenuItem tsmiFileExit;
        #endregion
        #region Windows Form Designer generated code
        /// <summary>Required method for Designer support</summary>
        void InitializeComponent() {
            this.components = new System.ComponentModel.Container();
            this.ms1 = new System.Windows.Forms.MenuStrip();
            this.tsmiFile = new System.Windows.Forms.ToolStripMenuItem();
            this.smiFileCreateClient = new System.Windows.Forms.ToolStripMenuItem();
            this.toolStripSeparator1 = new System.Windows.Forms.ToolStripSeparator();
            this.tsmiFileExit = new System.Windows.Forms.ToolStripMenuItem();
            this.gbLocations = new System.Windows.Forms.GroupBox();
            this.btnClearLocs = new System.Windows.Forms.Button();
            this.btnUpdateLoc = new System.Windows.Forms.Button();
            this.btnAddLoc = new System.Windows.Forms.Button();
            this.tbChecker = new System.Windows.Forms.TextBox();
            this.tbScanner = new System.Windows.Forms.TextBox();
            this.tbLocation = new System.Windows.Forms.TextBox();
            this.tbSubloc = new System.Windows.Forms.TextBox();
            this.label4 = new System.Windows.Forms.Label();
            this.label3 = new System.Windows.Forms.Label();
            this.label2 = new System.Windows.Forms.Label();
            this.label1 = new System.Windows.Forms.Label();
            this.lbLocations = new System.Windows.Forms.ListBox();
            this.tbServer = new System.Windows.Forms.TextBox();
            this.label6 = new System.Windows.Forms.Label();
            this.tbDatabase = new System.Windows.Forms.TextBox();
            this.label7 = new System.Windows.Forms.Label();
            this.btnSvrAvail = new System.Windows.Forms.Button();
            this.gbSN = new System.Windows.Forms.GroupBox();
            this.lbSN = new System.Windows.Forms.ListBox();
            this.pnlButtons = new System.Windows.Forms.Panel();
            this.btnClearService = new System.Windows.Forms.Button();
            this.btnClearList = new System.Windows.Forms.Button();
            this.btnAddServer = new System.Windows.Forms.Button();
            this.tbSN = new System.Windows.Forms.TextBox();
            this.label5 = new System.Windows.Forms.Label();
            this.btnAddSingle = new System.Windows.Forms.Button();
            this.errorProvider1 = new System.Windows.Forms.ErrorProvider(this.components);
            this.btnShowSNs = new System.Windows.Forms.Button();
            this.ms1.SuspendLayout();
            this.gbLocations.SuspendLayout();
            this.gbSN.SuspendLayout();
            this.pnlButtons.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.errorProvider1)).BeginInit();
            this.SuspendLayout();
            // 
            // ms1
            // 
            this.ms1.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.tsmiFile});
            this.ms1.Location = new System.Drawing.Point(0, 0);
            this.ms1.Name = "ms1";
            this.ms1.Size = new System.Drawing.Size(400, 24);
            this.ms1.TabIndex = 0;
            this.ms1.Text = "ms1";
            // 
            // tsmiFile
            // 
            this.tsmiFile.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.smiFileCreateClient,
            this.toolStripSeparator1,
            this.tsmiFileExit});
            this.tsmiFile.Name = "tsmiFile";
            this.tsmiFile.Size = new System.Drawing.Size(37, 20);
            this.tsmiFile.Text = "File";
            // 
            // smiFileCreateClient
            // 
            this.smiFileCreateClient.Name = "smiFileCreateClient";
            this.smiFileCreateClient.ShortcutKeys = ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.C)));
            this.smiFileCreateClient.Size = new System.Drawing.Size(182, 22);
            this.smiFileCreateClient.Text = "Create client";
            this.smiFileCreateClient.DropDownOpening += new System.EventHandler(this.smiFileCreateClient_DropDownOpening);
            this.smiFileCreateClient.Click += new System.EventHandler(this.smiFileCreateClient_Click);
            // 
            // toolStripSeparator1
            // 
            this.toolStripSeparator1.Name = "toolStripSeparator1";
            this.toolStripSeparator1.Size = new System.Drawing.Size(179, 6);
            // 
            // tsmiFileExit
            // 
            this.tsmiFileExit.Name = "tsmiFileExit";
            this.tsmiFileExit.Size = new System.Drawing.Size(182, 22);
            this.tsmiFileExit.Text = "Exit";
            this.tsmiFileExit.Click += new System.EventHandler(this.exitClick);
            // 
            // gbLocations
            // 
            this.gbLocations.Controls.Add(this.btnClearLocs);
            this.gbLocations.Controls.Add(this.btnUpdateLoc);
            this.gbLocations.Controls.Add(this.btnAddLoc);
            this.gbLocations.Controls.Add(this.tbChecker);
            this.gbLocations.Controls.Add(this.tbScanner);
            this.gbLocations.Controls.Add(this.tbLocation);
            this.gbLocations.Controls.Add(this.tbSubloc);
            this.gbLocations.Controls.Add(this.label4);
            this.gbLocations.Controls.Add(this.label3);
            this.gbLocations.Controls.Add(this.label2);
            this.gbLocations.Controls.Add(this.label1);
            this.gbLocations.Controls.Add(this.lbLocations);
            this.gbLocations.Location = new System.Drawing.Point(11, 73);
            this.gbLocations.Name = "gbLocations";
            this.gbLocations.Size = new System.Drawing.Size(367, 129);
            this.gbLocations.TabIndex = 1;
            this.gbLocations.TabStop = false;
            this.gbLocations.Text = "Locations";
            // 
            // btnClearLocs
            // 
            this.btnClearLocs.Location = new System.Drawing.Point(166, 99);
            this.btnClearLocs.Name = "btnClearLocs";
            this.btnClearLocs.Size = new System.Drawing.Size(75, 23);
            this.btnClearLocs.TabIndex = 6;
            this.btnClearLocs.Text = "Clear";
            this.btnClearLocs.UseVisualStyleBackColor = true;
            this.btnClearLocs.Click += new System.EventHandler(this.btnClearLocs_Click);
            // 
            // btnUpdateLoc
            // 
            this.btnUpdateLoc.Location = new System.Drawing.Point(90, 99);
            this.btnUpdateLoc.Name = "btnUpdateLoc";
            this.btnUpdateLoc.Size = new System.Drawing.Size(75, 23);
            this.btnUpdateLoc.TabIndex = 5;
            this.btnUpdateLoc.Text = "Update";
            this.btnUpdateLoc.UseVisualStyleBackColor = true;
            this.btnUpdateLoc.Click += new System.EventHandler(this.btnUpdateLoc_Click);
            // 
            // btnAddLoc
            // 
            this.btnAddLoc.Location = new System.Drawing.Point(9, 100);
            this.btnAddLoc.Name = "btnAddLoc";
            this.btnAddLoc.Size = new System.Drawing.Size(75, 23);
            this.btnAddLoc.TabIndex = 4;
            this.btnAddLoc.Text = "Add";
            this.btnAddLoc.UseVisualStyleBackColor = true;
            this.btnAddLoc.Click += new System.EventHandler(this.btnAddLoc_Click);
            // 
            // tbChecker
            // 
            this.tbChecker.Location = new System.Drawing.Point(93, 73);
            this.tbChecker.Name = "tbChecker";
            this.tbChecker.Size = new System.Drawing.Size(100, 20);
            this.tbChecker.TabIndex = 3;
            // 
            // tbScanner
            // 
            this.tbScanner.Location = new System.Drawing.Point(93, 53);
            this.tbScanner.Name = "tbScanner";
            this.tbScanner.Size = new System.Drawing.Size(100, 20);
            this.tbScanner.TabIndex = 2;
            // 
            // tbLocation
            // 
            this.tbLocation.Location = new System.Drawing.Point(93, 16);
            this.tbLocation.Name = "tbLocation";
            this.tbLocation.Size = new System.Drawing.Size(100, 20);
            this.tbLocation.TabIndex = 0;
            // 
            // tbSubloc
            // 
            this.tbSubloc.Location = new System.Drawing.Point(93, 36);
            this.tbSubloc.Name = "tbSubloc";
            this.tbSubloc.Size = new System.Drawing.Size(100, 20);
            this.tbSubloc.TabIndex = 1;
            // 
            // label4
            // 
            this.label4.AutoSize = true;
            this.label4.Location = new System.Drawing.Point(6, 80);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(79, 13);
            this.label4.TabIndex = 4;
            this.label4.Text = "Checker name:";
            // 
            // label3
            // 
            this.label3.AutoSize = true;
            this.label3.Location = new System.Drawing.Point(6, 60);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(79, 13);
            this.label3.TabIndex = 3;
            this.label3.Text = "Scanner name:";
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.Location = new System.Drawing.Point(19, 43);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(66, 13);
            this.label2.TabIndex = 2;
            this.label2.Text = "Sublocation:";
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Location = new System.Drawing.Point(34, 24);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(51, 13);
            this.label1.TabIndex = 1;
            this.label1.Text = "Location:";
            // 
            // lbLocations
            // 
            this.lbLocations.Dock = System.Windows.Forms.DockStyle.Right;
            this.lbLocations.FormattingEnabled = true;
            this.lbLocations.Location = new System.Drawing.Point(244, 16);
            this.lbLocations.Name = "lbLocations";
            this.lbLocations.Size = new System.Drawing.Size(120, 110);
            this.lbLocations.TabIndex = 7;
            this.lbLocations.SelectedIndexChanged += new System.EventHandler(this.lbLocations_SelectedIndexChanged);
            // 
            // tbServer
            // 
            this.tbServer.Location = new System.Drawing.Point(273, 20);
            this.tbServer.Name = "tbServer";
            this.tbServer.ReadOnly = true;
            this.tbServer.Size = new System.Drawing.Size(100, 20);
            this.tbServer.TabIndex = 3;
            // 
            // label6
            // 
            this.label6.AutoSize = true;
            this.label6.Location = new System.Drawing.Point(228, 24);
            this.label6.Name = "label6";
            this.label6.Size = new System.Drawing.Size(41, 13);
            this.label6.TabIndex = 13;
            this.label6.Text = "Server:";
            // 
            // tbDatabase
            // 
            this.tbDatabase.Location = new System.Drawing.Point(273, 40);
            this.tbDatabase.Name = "tbDatabase";
            this.tbDatabase.ReadOnly = true;
            this.tbDatabase.Size = new System.Drawing.Size(100, 20);
            this.tbDatabase.TabIndex = 4;
            // 
            // label7
            // 
            this.label7.AutoSize = true;
            this.label7.Location = new System.Drawing.Point(213, 44);
            this.label7.Name = "label7";
            this.label7.Size = new System.Drawing.Size(56, 13);
            this.label7.TabIndex = 15;
            this.label7.Text = "Database:";
            // 
            // btnSvrAvail
            // 
            this.btnSvrAvail.Location = new System.Drawing.Point(33, 27);
            this.btnSvrAvail.Name = "btnSvrAvail";
            this.btnSvrAvail.Size = new System.Drawing.Size(109, 23);
            this.btnSvrAvail.TabIndex = 0;
            this.btnSvrAvail.Text = "Enable Service";
            this.btnSvrAvail.UseVisualStyleBackColor = true;
            this.btnSvrAvail.Click += new System.EventHandler(this.btnSvrAvail_Click);
            // 
            // gbSN
            // 
            this.gbSN.Controls.Add(this.lbSN);
            this.gbSN.Controls.Add(this.pnlButtons);
            this.gbSN.Location = new System.Drawing.Point(12, 208);
            this.gbSN.Name = "gbSN";
            this.gbSN.Size = new System.Drawing.Size(383, 219);
            this.gbSN.TabIndex = 16;
            this.gbSN.TabStop = false;
            this.gbSN.Text = "Serial Numbers";
            // 
            // lbSN
            // 
            this.lbSN.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lbSN.FormattingEnabled = true;
            this.lbSN.Location = new System.Drawing.Point(136, 16);
            this.lbSN.Name = "lbSN";
            this.lbSN.Size = new System.Drawing.Size(244, 200);
            this.lbSN.TabIndex = 5;
            // 
            // pnlButtons
            // 
            this.pnlButtons.Controls.Add(this.btnShowSNs);
            this.pnlButtons.Controls.Add(this.btnClearService);
            this.pnlButtons.Controls.Add(this.btnClearList);
            this.pnlButtons.Controls.Add(this.btnAddServer);
            this.pnlButtons.Controls.Add(this.tbSN);
            this.pnlButtons.Controls.Add(this.label5);
            this.pnlButtons.Controls.Add(this.btnAddSingle);
            this.pnlButtons.Dock = System.Windows.Forms.DockStyle.Left;
            this.pnlButtons.Location = new System.Drawing.Point(3, 16);
            this.pnlButtons.Name = "pnlButtons";
            this.pnlButtons.Size = new System.Drawing.Size(133, 200);
            this.pnlButtons.TabIndex = 6;
            // 
            // btnClearService
            // 
            this.btnClearService.Location = new System.Drawing.Point(3, 103);
            this.btnClearService.Name = "btnClearService";
            this.btnClearService.Size = new System.Drawing.Size(119, 23);
            this.btnClearService.TabIndex = 6;
            this.btnClearService.Text = "Clear all from Service";
            this.btnClearService.UseVisualStyleBackColor = true;
            this.btnClearService.Click += new System.EventHandler(this.btnClearService_Click);
            // 
            // btnClearList
            // 
            this.btnClearList.Location = new System.Drawing.Point(3, 74);
            this.btnClearList.Name = "btnClearList";
            this.btnClearList.Size = new System.Drawing.Size(119, 23);
            this.btnClearList.TabIndex = 5;
            this.btnClearList.Text = "Clear List";
            this.btnClearList.UseVisualStyleBackColor = true;
            this.btnClearList.Click += new System.EventHandler(this.btnClearList_Click);
            // 
            // btnAddServer
            // 
            this.btnAddServer.Location = new System.Drawing.Point(3, 132);
            this.btnAddServer.Name = "btnAddServer";
            this.btnAddServer.Size = new System.Drawing.Size(119, 23);
            this.btnAddServer.TabIndex = 4;
            this.btnAddServer.Text = "Add all to Service";
            this.btnAddServer.UseVisualStyleBackColor = true;
            this.btnAddServer.Click += new System.EventHandler(this.btnAddServer_Click);
            // 
            // tbSN
            // 
            this.tbSN.Location = new System.Drawing.Point(3, 19);
            this.tbSN.Name = "tbSN";
            this.tbSN.Size = new System.Drawing.Size(100, 20);
            this.tbSN.TabIndex = 2;
            // 
            // label5
            // 
            this.label5.AutoSize = true;
            this.label5.Location = new System.Drawing.Point(13, 3);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(76, 13);
            this.label5.TabIndex = 3;
            this.label5.Text = "Serial Number:";
            // 
            // btnAddSingle
            // 
            this.btnAddSingle.Location = new System.Drawing.Point(3, 45);
            this.btnAddSingle.Name = "btnAddSingle";
            this.btnAddSingle.Size = new System.Drawing.Size(119, 23);
            this.btnAddSingle.TabIndex = 0;
            this.btnAddSingle.Text = "Add to List";
            this.btnAddSingle.UseVisualStyleBackColor = true;
            this.btnAddSingle.Click += new System.EventHandler(this.btnAddSingle_Click);
            // 
            // errorProvider1
            // 
            this.errorProvider1.ContainerControl = this;
            // 
            // btnShowSNs
            // 
            this.btnShowSNs.Location = new System.Drawing.Point(3, 161);
            this.btnShowSNs.Name = "btnShowSNs";
            this.btnShowSNs.Size = new System.Drawing.Size(119, 23);
            this.btnShowSNs.TabIndex = 7;
            this.btnShowSNs.Text = "Show all S/Ns";
            this.btnShowSNs.UseVisualStyleBackColor = true;
            this.btnShowSNs.Click += new System.EventHandler(this.btnShowSNs_Click);
            // 
            // driverForm
            // 
            this.ClientSize = new System.Drawing.Size(400, 448);
            this.Controls.Add(this.gbSN);
            this.Controls.Add(this.btnSvrAvail);
            this.Controls.Add(this.tbDatabase);
            this.Controls.Add(this.label7);
            this.Controls.Add(this.tbServer);
            this.Controls.Add(this.label6);
            this.Controls.Add(this.gbLocations);
            this.Controls.Add(this.ms1);
            this.MainMenuStrip = this.ms1;
            this.Name = "driverForm";
            this.Load += new System.EventHandler(this.formLoad);
            this.ms1.ResumeLayout(false);
            this.ms1.PerformLayout();
            this.gbLocations.ResumeLayout(false);
            this.gbLocations.PerformLayout();
            this.gbSN.ResumeLayout(false);
            this.pnlButtons.ResumeLayout(false);
            this.pnlButtons.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.errorProvider1)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }
        #endregion
        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        protected override void Dispose(bool disposing) {
            if (disposing) {
                if ((components != null)) {
                    components.Dispose();
                }
            }
            base.Dispose(disposing);
        }

        private GroupBox gbLocations;
        private Button btnClearLocs;
        private Button btnUpdateLoc;
        private Button btnAddLoc;
        private TextBox tbChecker;
        private TextBox tbScanner;
        private TextBox tbLocation;
        private TextBox tbSubloc;
        private Label label4;
        private Label label3;
        private Label label2;
        private Label label1;
        private ListBox lbLocations;
        private TextBox tbServer;
        private Label label6;
        private TextBox tbDatabase;
        private Label label7;
        private Button btnSvrAvail;
        private GroupBox gbSN;
        private Panel pnlButtons;
        private Button btnAddSingle;
        private ListBox lbSN;
        private Label label5;
        private TextBox tbSN;
        private Button btnClearService;
        private Button btnClearList;
        private Button btnAddServer;
        private ErrorProvider errorProvider1;
        private ToolStripMenuItem smiFileCreateClient;
        private ToolStripSeparator toolStripSeparator1;
        private Button btnShowSNs;
    }
}
